# Generated by Django 5.0.2 on 2024-02-21 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тема рассылки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало')),
                ('next_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующее')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Конец')),
                ('periodicity', models.CharField(choices=[('once_a_day', 'once_a_day'), ('once_a_week', 'once_a_week'), ('once_a_month', 'once_a_month')], default='once_a_day', verbose_name='Интервал')),
                ('status', models.CharField(choices=[('start', 'start'), ('finish', 'finish'), ('created', 'created')], default='created', verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('client', models.ManyToManyField(to='mailing.client', verbose_name='Клиент')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
